COMPONENTS_CONNECTIVITY_INCLUDE :=

ifeq ($(LOSCFG_COMPONENTS_CONNECTIVITY_AGENTTINY), y)
include $(LITEOSTOPDIR)/components/connectivity/agent_tiny/agent_tiny.mk
COMPONENTS_CONNECTIVITY_INCLUDE += $(ATINY_TINY_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_CONNECTIVITY_MQTT), y)
include $(LITEOSTOPDIR)/components/connectivity/mqtt/mqtt.mk
COMPONENTS_CONNECTIVITY_INCLUDE += $(COMPONENTS_MQTT_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_CONNECTIVITY_LWM2M), y)
include $(LITEOSTOPDIR)/components/connectivity/lwm2m/lwm2m.mk
COMPONENTS_CONNECTIVITY_INCLUDE += $(COMPONENTS_LWM2M_INCLUDE)
endif

include $(LITEOSTOPDIR)/components/connectivity/atiny_log/atiny_log.mk
COMPONENTS_CONNECTIVITY_INCLUDE += $(COMPONENTS_ATINY_LOG_INCLUDE)

ifeq ($(LOSCFG_COMPONENTS_CONNECTIVITY_NB_IOT), y)
include $(LITEOSTOPDIR)/components/connectivity/nb_iot/nb_iot.mk
COMPONENTS_CONNECTIVITY_INCLUDE += $(COMPONENTS_NB_IOT_INCLUDE)
endif
