COMPONENTS_UTILITY_INCLUDE :=

ifeq ($(LOSCFG_COMPONENTS_ICONV), y)
include $(LITEOSTOPDIR)/components/utility/iconv/iconv.mk
COMPONENTS_UTILITY_INCLUDE += $(COMPONENTS_ICONV_INCLUDE)
endif
ifeq ($(LOSCFG_COMPONENTS_INIPARSER), y)
include $(LITEOSTOPDIR)/components/utility/iniparser/iniparser.mk
COMPONENTS_UTILITY_INCLUDE += $(COMPONENTS_INIPARSER_INCLUDE)
endif
ifeq ($(LOSCFG_COMPONENTS_BIDIREFERENCE), y)
include $(LITEOSTOPDIR)/components/utility/bidireference/bidireference.mk
COMPONENTS_UTILITY_INCLUDE += $(COMPONENTS_BIDIREFERENCE_INCLUDE)
endif
