
include $(LITEOSTOPDIR)/config.mk
include $(LITEOSTOPDIR)/components/utility/genann/genann.mk

MODULE_NAME := genann_demo

LOCAL_INCLUDE := $(COMPONENTS_GENANN_INCLUDE)

LOCAL_SRCS := $(wildcard *.c)

LOCAL_FLAGS := $(LOCAL_INCLUDE)

include $(MODULE)
