include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := pdfgen_demo

LOCAL_SRCS = $(wildcard pdfgen_demo.c)

LOCAL_INCLUDE := $(COMPONENTS_PDFGEN_INCLUDE)
LOCAL_INCLUDE += -I $(LITEOSTOPDIR)/demos/utility/pdfgen

LOCAL_FLAGS := $(LOCAL_INCLUDE)

include $(MODULE)
