COMPONENTS_MEDIA_INCLUDE :=

ifeq ($(LOSCFG_COMPONENTS_LIBPNG), y)
include $(LITEOSTOPDIR)/components/media/libpng/libpng.mk
COMPONENTS_MEDIA_INCLUDE += $(COMPONENTS_LIBPNG_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_OPUS), y)
include $(LITEOSTOPDIR)/components/media/opus/opus.mk
COMPONENTS_MEDIA_INCLUDE += $(COMPONENTS_OPUS_INCLUDE)
endif
