COMPONENTS_SECURITY_INCLUDE :=

CLASS_DIR := $(LITEOSTOPDIR)/components/security

ifeq ($(LOSCFG_COMPONENTS_SECURITY_MBEDTLS), y)
include $(CLASS_DIR)/mbedtls/mbedtls.mk
COMPONENTS_SECURITY_INCLUDE += $(COMPONENTS_MBEDTLS_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_OPENSSL), y)
include $(CLASS_DIR)/openssl/openssl.mk
COMPONENTS_SECURITY_INCLUDE += $(COMPONENTS_OPENSSL_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_RHASH), y)
include $(CLASS_DIR)/rhash/rhash.mk
COMPONENTS_SECURITY_INCLUDE += $(COMPONENTS_RHASH_INCLUDE)
endif

ifeq ($(LOSCFG_COMPONENTS_TINYCRYPT), y)
include $(CLASS_DIR)/tinycrypt/tinycrypt.mk
COMPONENTS_SECURITY_INCLUDE += $(COMPONENTS_TINYCRYPT_INCLUDE)
endif

