include $(LITEOSTOPDIR)/config.mk
include $(LITEOSTOPDIR)/components/utility/genann/genann.mk

MODULE_NAME := genann

LOCAL_INCLUDE := $(COMPONENTS_GENANN_INCLUDE)

LOCAL_SRCS := $(GENANN_VERSION)/genann.c $(GENANN_VERSION)/example1.c $(GENANN_VERSION)/example2.c

LOCAL_CPPFLAGS := $(LOCAL_INCLUDE)

include $(MODULE)
