include $(LITEOSTOPDIR)/config.mk
include $(LITEOSTOPDIR)/components/utility/jsoncpp/jsoncpp.mk

MODULE_NAME := jsoncpp_demo

LOCAL_SRCS := $(wildcard *.cpp)

LOCAL_INCLUDE := $(COMPONENTS_JSONCPP_INCLUDE)

LOCAL_CPPFLAGS :=  $(LOCAL_INCLUDE) -w -std=c++11

include $(MODULE)
