include $(LITEOSTOPDIR)/config.mk
include $(LITEOSTOPDIR)/components/media/openexif/openexif.mk

MODULE_NAME := $(notdir $(CURDIR))

LOCAL_INCLUDE := \
    -I $(LITEOSTOPDIR)/include/fs \
    -I $(LITEOSTOPDIR)/components/media/openexif/$(OPENEXIF_VERSION)/src \
    -I $(LITEOSTOPDIR)/components/media/openexif/$(OPENEXIF_VERSION)/src/OpenExifJpeg

LOCAL_SRCS = $(wildcard $(OPENEXIF_VERSION)/src/*.cpp) \
    $(wildcard $(OPENEXIF_VERSION)/src/OpenExifJpeg/*.cpp)

LOCAL_CPPFLAGS := $(LOCAL_INCLUDE) -w -DOPENEXIF_NO_IJG

include $(MODULE)
