/*
 * Automatically generated C config: don't edit
 */
/*
 * Version Number
 */
#ifndef LOSCFG_MODULE_SWITCH
#define LOSCFG_MODULE_SWITCH
/*
 * Compiler
 */
#undef LOSCFG_COMPILER_HIMIX_32
#undef LOSCFG_COMPILER_HIMIX100_64
#undef LOSCFG_COMPILER_HCC_64
#undef LOSCFG_COMPILER_XTENSA_32
#define LOSCFG_COMPILER_ARM_NONE_EABI 1

/*
 * Platform
 */
#define LOSCFG_PLATFORM "Cloud_STM32F429IGTx_FIRE"
#undef LOSCFG_PLATFORM_HI3556V200
#undef LOSCFG_PLATFORM_HI1980_IMU
#undef LOSCFG_PLATFORM_QEMU_VIRT_A53
#undef LOSCFG_PLATFORM_PBX_A9
#undef LOSCFG_PLATFORM_V900_IVP
#define LOSCFG_PLATFORM_STM32F429IGTX 1
#undef LOSCFG_PLATFORM_STM32F769IDISCOVERY
#define LOSCFG_PLATFORM_BSP_GIC_V2 1
#undef LOSCFG_PLATFORM_BSP_GIC_V3
#undef LOSCFG_PLATFORM_BSP_XTENSA_XEA3
#define LOSCFG_ARCH_ARM_AARCH32 1
#define LOSCFG_ARCH_FPU_VFP_V4 1
#define LOSCFG_ARCH_FPU_VFP_D16 1
#define LOSCFG_ARCH_FPU "fpv4-sp-d16"
#define LOSCFG_ARCH_CORTEX_M4 1
#define LOSCFG_ARCH_CPU "cortex-m4"

/*
 * Extra Configurations
 */
#define LOSCFG_ARCH_FPU_DISABLE 1
#define LOSCFG_IRQ_USE_STANDALONE_STACK 1

/*
 * Kernel
 */
#define LOSCFG_KERNEL_LITEKERNEL 1
#undef LOSCFG_KERNEL_MEM_BESTFIT
#define LOSCFG_KERNEL_MEM_BESTFIT_LITTLE 1
#define LOSCFG_KERNEL_EXTKERNEL 1
#define LOSCFG_KERNEL_CPPSUPPORT 1
#undef LOSCFG_KERNEL_MPU
#define LOSCFG_KERNEL_CPUP 1
#define LOSCFG_CPUP_INCLUDE_IRQ 1
#undef LOSCFG_KERNEL_DYNLOAD
#define LOSCFG_KERNEL_TICKLESS 1
#undef LOSCFG_KERNEL_TRACE
#undef LOSCFG_KERNEL_SMP
#define LOSCFG_SCHED_SQ 1
#undef LOSCFG_SCHED_MQ

/*
 * Lib
 */
#define LOSCFG_LIB_LIBC 1
#undef LOSCFG_NO_LIBC
#define LOSCFG_LIB_LIBM 1
#undef LOSCFG_NO_LIBC

/*
 * Compat
 */
#undef LOSCFG_COMPAT_CMSIS
#define LOSCFG_COMPAT_POSIX 1

/*
 * Debug
 */
#undef LOSCFG_COMPILE_DEBUG
#undef LOSCFG_PLATFORM_ADAPT
#undef LOSCFG_COREDUMP
#undef LOSCFG_GDB
#undef LOSCFG_ENABLE_MAGICKEY
#undef LOSCFG_THUMB
#undef LOSCFG_DEBUG_VERSION
#define LOSCFG_PLATFORM_UART_WITHOUT_VFS 1
#undef LOSCFG_PLATFORM_NO_UART
#define LOSCFG_SERIAL_OUTPUT_ENABLE 1

/*
 * TestSuite or AppInit
 */
#define LOSCFG_PLATFORM_OSAPPINIT 1
#undef LOSCFG_TEST
#undef LOSCFG_TESTSUIT_SHELL
#undef LOSCFG_TEST_MANUAL_TEST
#undef LOSCFG_FUZZ_DT

/*
 * Stack Smashing Protector (SSP) Compiler Feature
 */
#undef LOSCFG_CC_NO_STACKPROTECTOR
#undef LOSCFG_CC_STACKPROTECTOR
#define LOSCFG_CC_STACKPROTECTOR_STRONG 1
#undef LOSCFG_CC_STACKPROTECTOR_ALL

#endif
